import json
from pathlib import Path

root = Path(__file__).parent
inventory = json.loads((root/'current-question-inventory.json').read_text(encoding='utf-8'))
rows = []
def add(section, old, title, draft=None, source=None):
    rows.append(dict(section=section, old=old, title=title, draft=draft, source=source))

add('8.2',1,'Thermal equilibrium')
add('8.2',2,'A physical property used by a thermometer')
add('8.2',4,'Equilibrium with the room', 'A cup of hot water is left in a room whose temperature remains constant. After enough time for thermal equilibrium, how will the temperatures of the water, cup, and room compare? Explain.')
add('8.2',5,'One Celsius-to-kelvin calculation', 'A person has a temperature of 39.0 °C. What is this temperature in kelvins? Would changing the temperature scale change whether the person has a fever? Explain.')
add('8.2',None,'Temperature changes versus temperature readings', 'A sample warms from 20 °C to 30 °C. What is its temperature change in degrees Celsius and in kelvins? Why do its temperature readings differ between the two scales even though the temperature changes have the same numerical value?', 'Temperature Scales – Definition – Q1')
add('8.3',13,'Limits of the ideal-gas model')
add('8.3',14,'Constant-volume gas thermometer')
add('8.3',None,'Ideal-gas predictions', 'For a fixed amount of ideal gas, predict what happens to its temperature when (a) its pressure increases at constant volume, (b) its volume decreases at constant pressure, and (c) its pressure doubles while its volume is halved. Explain each prediction.', 'Ideal Gas Law – Descriptions – Q2')
add('8.3',None,'Recognizing insufficient information', 'A fixed amount of ideal gas expands. Is that information alone enough to determine whether its temperature increases, decreases, or stays the same? Explain what additional information would allow you to decide.', 'Ideal Gas Law – Descriptions – Q2; also its test-bank version')
add('8.3',20,'A short pressure–volume calculation', 'A sealed flexible bag contains 100 mL of air at an absolute pressure of 100 kPa. The surrounding pressure falls to 75 kPa. Assume the air stays at the same temperature, no air escapes, and the bag expands until its internal pressure equals the surrounding pressure. What is its final volume? Explain why the direction of the change makes sense.')
add('8.4',26,'Direction of heat transfer')
add('8.4',28,'Is heat stored in an object?')
add('8.4',27,'Heat transfer and work can produce similar effects', 'Water can become warmer either by contact with a hotter object or by stirring it in an insulated container. How does energy enter the water in each case? What can happen to the water’s internal energy?', 'Heat – Descriptions – Q1')
add('8.5',None,'Recognizing the three transfer mechanisms', 'Identify the main heat-transfer mechanism in each case: (a) energy passes along a stationary metal spoon from its hot end, (b) warm water circulates through a cooler region of a pot, and (c) sunlight warms your skin. Which mechanism can transfer energy across a vacuum?', 'Heat – Transfer Methods – Q1 and Q2')
add('8.5',31,'Thermos bottle', 'A thermos bottle has two walls separated by a vacuum, silvered surfaces that reflect infrared radiation, and a tightly fitting stopper made from a material that conducts heat poorly.\n\n(a) How does the vacuum reduce heat transfer by conduction and convection?\n\n(b) Why can radiation still transfer energy across the vacuum, and how do the silvered surfaces reduce this transfer?\n\n(c) How does the stopper help reduce heat transfer?\n\n(d) Explain why the same thermos can keep a hot drink hot and a cold drink cold.')
add('8.6',32,'Factors determining heat needed for a temperature change')
add('8.6',None,'Specific-heat comparison with a short calculation', 'Equal 1.0-kg samples of water and steel each absorb 4.2 kJ, with no phase change or work done. Use specific heats of 4200 J/(kg·°C) for water and 450 J/(kg·°C) for steel. (a) Predict which sample has the larger temperature rise. (b) Calculate each rise. Explain how your results reflect specific heat.', 'Heat Capacity – Calculations – Q1; qualitative test-bank version')
add('8.6',None,'Mixing warm and cool water', 'Equal masses of water at 20 °C and 60 °C are mixed in an insulated container of negligible heat capacity. (a) What is the final temperature? (b) If the mass of the cooler water were greater, would the final temperature be above or below your answer to (a)? Explain. Assume no phase change and constant specific heat.', 'Heat Capacity – Calculations – Q2')
add('8.6',33,'Brake temperature and initial speed')
add('8.6',40,'Oakland–Orinda temperature comparison', 'Oakland, California, lies beside San Francisco Bay and is exposed to cool marine air. Orinda is a short distance inland, east of Oakland, with hills between it and the bay that reduce this marine influence. On a hot summer day, Orinda can be considerably warmer than Oakland. How does the large specific heat of water help explain why the nearby water moderates Oakland’s temperature? Explain why water warms more slowly than land during the day and cools more slowly as temperatures fall.', 'Heat Capacity – Applications – Q1 (Oakland/Orinda); geographic context added at maintainer request; replaces current Exercise 40')
add('8.7',None,'Energy absorbed or released during phase changes', 'For each process, state whether the substance absorbs or releases energy as heat: (a) melting, (b) freezing, (c) vaporization, and (d) condensation. Explain briefly in terms of changes in molecular interactions.', 'Latent Heat – Descriptions – Q1')
add('8.7',None,'Why temperature can remain constant during heating', 'Heat is transferred into a mixture of ice and liquid water at its melting temperature. Why can the ice melt without the temperature rising? Explain where the added energy goes.', 'Latent Heat – Descriptions – Q2')
add('8.7',37,'Ice and water in thermal equilibrium', 'Ice and liquid water are in thermal equilibrium at 0°C in an insulated container, also at 0°C, at ordinary atmospheric pressure. Will the total amount of ice increase, decrease, or remain the same? Explain. Does this mean that no molecules move between the ice and liquid water?')
add('8.7',38,'Condensation on a glass of ice water')
add('8.7',None,'Read the existing heating curve', 'Use the heating curve in Section 8.7 for the same fixed mass of water at atmospheric pressure. Rank the energy inputs required to (a) warm ice from −20 °C to 0 °C, (b) melt all the ice at 0 °C, (c) warm the liquid from 0 °C to 100 °C, and (d) vaporize all the liquid at 100 °C. Explain how the horizontal lengths of the graph support your ranking.', 'Latent Heat – Descriptions – Q3; also its test-bank version')
add('8.7',30,'Evaporation and cooling the body', 'Sweat on exposed skin can evaporate, while sweat on skin submerged in warm water cannot evaporate directly into the air. Explain why evaporation can cool the body and why this cooling mechanism is unavailable to submerged skin.', 'Thermal Physics – Cooling Processes (essay question); retain the useful idea from the hot-tub question')
add('8.8',46,'First law as conservation of energy')
add('8.8',47,'Stored internal energy versus transfers by heat and work')
add('8.8',None,'One first-law energy balance', 'A closed system absorbs 500 J as heat and does 200 J of work on its surroundings. (a) How does its internal energy change? (b) Starting from the same initial state, suppose instead that 200 J of work is done on it while it absorbs the same heat. How does its internal energy change now? Explain the difference.', 'Thermodynamics – First Law – Q1; Lecture 17, Sections 3 and 5')
add('8.9',54,'Constant-volume heating', 'A fixed amount of gas is heated in a rigid sealed container. Assume there is no work other than possible expansion or compression work. Does the gas do work? What happens to its internal energy? Explain using the first law.', 'Thermodynamics – Processes – Q2')
add('8.9',55,'Isothermal expansion', 'A fixed amount of ideal gas expands isothermally and does work on a piston. Does its internal energy change? Must energy enter or leave as heat? Explain using the first law.', 'Thermodynamics – Processes – Q3')
add('8.9',56,'Adiabatic expansion', 'A fixed amount of ideal gas expands against a piston and does work while no heat is transferred. What happens to its internal energy and temperature? Explain using the first law.', 'Thermodynamics – Processes – Q4')
add('8.9',57,'When the adiabatic approximation is useful')
add('8.10',60,'Why a heat engine needs a temperature difference')
add('8.10',None,'Heat-engine work and efficiency', 'During each complete cycle, a heat engine absorbs 600 J from a hot reservoir and releases 400 J to a cold reservoir. (a) How much net work does it do? (b) What is its efficiency? (c) Does the energy released to the cold reservoir disappear? Explain.', 'Thermodynamics – Efficiency – Q1')
add('8.11',63,'Why the drinking bird eventually stops')
add('8.11',64,'Can engineering eliminate waste heat?')
add('8.11',65,'Second law versus energy conservation')
add('8.11',72,'Evaluate an engine claim', 'A proposed cyclic heat engine operates between reservoirs at 600 K and 300 K and absorbs 100 J from the hot reservoir each cycle. (a) What is its maximum possible efficiency? (b) Could it deliver 60 J of work per cycle? (c) Would a claim of 40 J per cycle prove that the engine actually works? Explain what the theoretical limit does and does not tell you.')
add('8.12',77,'Temperature difference and heat-pump performance', 'For an ideal heat pump maintaining the same indoor temperature, why does a colder outdoor temperature require more work to deliver the same amount of energy indoors? Relate your answer to the coefficient of performance.')
add('8.12',79,'Why an open refrigerator cannot cool the kitchen')
add('8.12',None,'COP greater than one and conservation of energy', 'A heat pump uses 1.0 kJ of electrical work to deliver 3.0 kJ to a room. (a) How much energy does it take from outdoors? (b) What is its coefficient of performance in heating mode? (c) Explain why delivering more energy than the electrical input does not violate conservation of energy.', 'Thermal Physics – Heat Pump Coefficient of Performance (essay); Heat Pump – Efficiency – Q1')
add('8.13',91,'Freezing and the entropy of the surroundings')
add('8.13',92,'Temperature differences and useful work', 'Two bodies at different temperatures exchange heat inside an isolated enclosure until they reach the same temperature. What happens to their combined entropy? Why does reaching a common temperature reduce the opportunity to obtain work from them using a heat engine?')
add('8.13',94,'Free expansion and irreversibility', 'A gas initially occupies one half of an insulated container; the other half is a vacuum. A partition is removed, and the gas expands freely into the empty half.\n\n(a) Why is this process irreversible?\n\n(b) No heat is transferred during the expansion. Does this mean that the gas’s entropy remains unchanged? Explain why substituting Q = 0 into ΔS = Q_rev/T, the relation for reversible heat transfer at constant temperature, would not correctly determine the entropy change in this free expansion.')
add('8.14',104,'A small, concrete microstate-counting example', 'Three distinguishable fair coins are tossed independently. (a) List the eight possible sequences of heads and tails. (b) How many sequences give exactly two heads? How many give three heads? (c) Which macrostate is more likely, and why? Explain how counting possible microscopic arrangements helps motivate the statistical interpretation of entropy.')
add('8.14',97,'Gas volume and available microscopic arrangements')

assert len(rows)==47, len(rows)
kept={r['old'] for r in rows if r['old'] is not None}
groups=[
 ('Repeated or algebra-heavy numerical practice', list(range(6,13))+[15,16,17,18,19,21,22,23,24,25]+list(range(66,72))+[73,74]+list(range(80,90))+list(range(98,104))+[105], 'Replace these clusters with the short calculations and predictions in the proposed set. Some are supported by the text; removal is about emphasis and repetition, not a claim that all are out of scope.'),
 ('Specialized setup or substantial background beyond the instructional payoff',[3,29,42,44,59,61,76,78,95], 'Thermometer transient response, Earth-interior transport, freeze-drying, cryogenic identification, long driving-energy estimate, metabolism comparison, building/store assumptions, and stellar entropy add setup or prerequisite burden.'),
 ('Overlap, vague framing, or an avoidable misleading premise',[34,35,36,39,41,43,45,48,49,50,51,52,53,58,62,75,90,93,96], 'Retained or replacement questions cover the core ideas more directly. In particular, avoid implying that all expansion cools a gas, that heat must pass through a particular energy form first, or that visually messy macroscopic objects are a reliable measure of thermodynamic entropy.')
]
removed=set().union(*(set(g[1]) for g in groups))
assert kept.isdisjoint(removed)
assert kept|removed == set(range(1,106)), sorted(set(range(1,106))-(kept|removed))
new=sum(r['old'] is None for r in rows)
out=['# Chapter 8 question-set proposal','', 'Status: proposal only; no exercise edits or preview refresh performed. Current numbers refer to preview version 58. Prepared 2026-09-30.','',f'Recommend **47 questions**: {len(kept)} retained or revised existing questions plus {new} MyOpenMath-based additions; {len(removed)} existing questions removed. This count follows coverage, not a preset quota. Preserve all five inline Check Your Understanding items.','', '## Basis and scope','', 'Reviewed the current 105-question inventory, maintained abridged sections 8.2–8.14, and the local September 27 MyOpenMath export. The crosswalk has 81 Chapter 8 records, including test-bank variants and lecture comprehension sets; these are not 81 distinct additions. The proposal favors prediction, explanation, short energy balances, and graph reading. No combinatorial formulas or logarithm calculations are required.','', 'The approved temperature-summary edit remains pending for the next refresh: one Celsius-to-kelvin relation inline, with the section body unchanged. This proposal does not restore Fahrenheit-conversion formulas.','', 'MyOpenMath sources below abbreviate the common “Introduction to Physics” prefix. Ordinary sources occur in **Question Set 7: Thermodynamics** and **Question Set 7 Assessment**, with archived reading/exercise copies. Test-bank variants occur in **Multiple-Choice Timed Assessment for Chapter 8**. Essay sources occur in **Essay Timed Assessment for Chapter 8** and **Take-Home Option A Final Exam**. Lecture 17 comprehension provides coverage context rather than text to copy. These are adaptations, not unreviewed imports of distractors, answers, or hints.','', '## Proposed set, in topic order','']
sec=None
for i,r in enumerate(rows,1):
 if sec!=r['section']:
  sec=r['section'];out+=['',f'### Section {sec}','']
 label=f"current Exercise {r['old']}" if r['old'] else 'new adaptation'
 out += [f"**{i}. {r['title']}** ({label}).",'']
 if r['draft']: out += [r['draft'],'']
 else:
  q=next(q for q in inventory if q['number']==r['old']);out += ['Retain: '+q['text'],'']
 if r['source']: out += ['Source comparison: '+r['source']+'.','']
out += ['## Removal groups','']
for title,nums,reason in groups:
 out += [f'### {title}','', 'Current exercises: '+', '.join(map(str,nums))+'.','',reason,'']
out += ['## Coverage findings and remaining optional choice','', '- **Thermos (current 31): retain the approved simplified version.** Supply the infrared-reflection property in the question and focus on the vacuum, silvered surfaces, stopper, and keeping drinks hot or cold. Retain its existing cutaway figure. No emissivity definition or formula is required.', '- **Statistical interpretation: recommend retain the three-coin exercise.** It follows the section’s explicit microstate model, gives students a manageable counting task, and replaces the large-number/logarithm exercises. If even that feels excessive, ask students to compare counts supplied in the existing five-coin table instead; the count remains 47.', '- **Heat transfer:** the new recognition question stays within the definitions actually taught. The existing inline everyday-example question remains; the new question adds explicit classification and vacuum transfer.', '- **Climate:** use one water-specific-heat question in 8.6, combining the purpose of current 40 and the Oakland/Orinda MyOpenMath question. Do not add a second regional climate question or imply that water heat capacity alone explains every local weather difference.', '- **Phase change:** use the existing heating-curve figure in m67124, ID `import-auto-id2928714`. Confirm its rendered number when implemented. The question specifies the same sample and atmospheric pressure; no new figure is needed.', '- **Processes:** the abridged body explicitly teaches isobaric, isochoric, isothermal, and adiabatic processes. The ideal-gas prediction question covers constant pressure, and the three energy-transfer questions cover the other processes. Specify ideal gas and expansion work where needed.', '- **Entropy:** the body explicitly says no logarithm calculations are needed. Retain explanation and elementary counting; avoid equating visual messiness with entropy. The free-expansion question links 8.13 to the existing 8.14 gas discussion and distinguishes actual heat transfer from heat transfer along a reversible path; it does not label free expansion adiabatic.', '', '## Implementation after approval','', 'Apply the retained/revised/new set, preserving stable source IDs for retained questions; move the climate question to 8.6 and the hot-tub replacement to 8.7. Retain the drinking-bird question’s previously approved wording. Remove obsolete figure references only with their removed questions; preserve figures that remain in use. Add the heating-curve cross-reference and check all section exercise links. Renumber the set in topic order, build and validate, then refresh only when requested. No ordinary-exercise answer key is proposed.','', '## Complete disposition by current number','', '| Current | Section | Decision | Proposed number / reason |','|---|---|---|---|']
for q in inventory:
 matches=[(i,r) for i,r in enumerate(rows,1) if r['old']==q['number']]
 if matches:
  i,r=matches[0];decision='Revise' if r['draft'] else 'Retain';reason=str(i)+(f"; move to {r['section']}" if q['section']!=r['section'] else '')
 else: decision='Remove';reason=next(g[0] for g in groups if q['number'] in g[1])
 out += [f"| {q['number']} | {q['section']} | {decision} | {reason} |"]
(root/'question-set-proposal.md').write_text('\n'.join(out)+'\n',encoding='utf-8')
(root/'question-set-proposal.json').write_text(json.dumps({'status':'proposal-only','questions':rows,'removal_groups':[dict(reason=t,numbers=n,explanation=e) for t,n,e in groups]},indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print(f'{len(rows)} proposed; {len(kept)} existing; {new} new; {len(removed)} removals; all 105 accounted for')
