from pathlib import Path
import re,json,hashlib,xml.etree.ElementTree as E
ROOT=Path(__file__).resolve().parents[1]
items=[('m71411','ex-cart-work-net-work','Work - Calculation - Q2','A shopper pushes a grocery cart 10 m across a level floor at constant speed, using a horizontal force of 20 N. (a) How much work does the shopper do? (b) What is the net work done on the cart? (c) How much work do the resistive forces do? Explain how your answers are consistent with the cart’s constant speed.'),('m71411','ex-kinetic-energy-scaling','Kinetic Energy - Scaling - Q1','A car increases its speed from 30 mph to 60 mph. (a) By what factor does its kinetic energy change? (b) By what factor would its kinetic energy change if its mass doubled while its speed remained unchanged? Explain.'),('m71414','ex-package-lifting-energy','Gravitational Potential Energy - Calculation - Q1','A delivery driver lifts a 10-kg package through a height of 0.50 m to load it into a truck. Use <m:math><m:mi>g</m:mi><m:mo>≈</m:mo><m:mn>10</m:mn><m:mspace width="0.1667em"/><m:mtext>m/s²</m:mtext></m:math>. (a) By how much does its gravitational potential energy increase? (b) Where does this energy come from? (c) How much work does gravity do on the package? Include the sign.'),('m67037','ex-comparing-paths-friction','Conservative Forces - Path Independence - Q1','Consider the two paths in <link target-id="import-auto-id2687249"/>. The toy car is launched with the same spring compression on either path. Assume it reaches the common endpoint on both paths. (a) If friction is negligible, must its final speed be the same on both paths? (b) Must the work done by gravity be the same? (c) If friction is significant, must its final speed still be the same? Briefly explain each answer.'),('m67045','ex-spring-energy-scaling','Work and Energy - Energy Formulas - Q1','A spring is compressed twice as far as before, within the range where Hooke’s law applies. (a) By what factor does the required holding force increase? (b) By what factor does the stored elastic potential energy increase? Explain why the factors differ.')]
orders={'m67539':['fs-id2189314','fs-id1913046','fs-id1268060'],'m71411':['fs-id1422290','fs-id2008777','ex-cart-work-net-work','ex-kinetic-energy-scaling','fs-id1527618'],'m71414':['ex-package-lifting-energy','fs-id1759147','fs-id1415865'],'m67037':['fs-id2769430','fs-id1707793','fs-id2731704','fs-id1862083','ex-comparing-paths-friction','fs-id1172158','fs-id1528780','fs-id1471362','fs-id2075302'],'m67045':['fs-id2008703','ex-spring-energy-scaling'],'m71415':['fs-id1299861','fs-id2072181','fs-id1354581']}
exportpath=ROOT.parent/'reference-inputs/phys-10-full-export-2026-09-27.imas';export=json.loads(exportpath.read_text(encoding='utf8'));sources={q['description']:q for q in export['questionset'].values()};lp=ROOT/'maintained/editorial-changes.json';ledger=json.loads(lp.read_text(encoding='utf8'));sha=lambda s:hashlib.sha256(s.encode()).hexdigest();provenance=[]
for mid,order in orders.items():
 rid='EX-C3-ADD-ORDER-'+mid;rp=Path('proposals/author-corrections')/(rid+'.json');assert rp.as_posix() not in ledger['changes']
 p=ROOT/f'maintained/modules/{mid}/index.cnxml';before=p.read_text(encoding='utf8');g=re.search(r'<section\b[^>]*class="conceptual-questions"[^>]*>.*?</section>',before,re.S);assert g,mid;block=g[0];added=[]
 for mod,eid,title,question in items:
  if mod!=mid:continue
  desc='Introduction to Physics - '+title+' (updated to LibreTexts version)';q=sources[desc]
  addition=dict(id=eid,source_description=desc,assessment='Question Set 4: Energy and Momentum',source_uniqueid=str(q['uniqueid']),source_export_sha256=hashlib.sha256(exportpath.read_bytes()).hexdigest(),author=q['author'],export_license_code=q['license'],upstream_attribution=q.get('otherattribution'),adaptation='Approved fixed conceptual or short-calculation adaptation; spring scaling extends formula identification; path question uses existing recovered figure.')
  added.append(addition);provenance.append(addition)
  block=block.replace('</section>',f'<exercise id="{eid}" type="conceptual-questions"><problem id="{eid}-problem"><para id="{eid}-p1">{question}</para></problem></exercise>\n</section>')
 hits=list(re.finditer(r'<exercise\b[^>]*id="([^"]+)"[^>]*>.*?</exercise>',block,re.S));parts={m[1]:m[0] for m in hits};assert set(parts)==set(order),(mid,set(parts)^set(order));block=block[:hits[0].start()]+'\n'.join(parts[i] for i in order)+block[hits[-1].end():];after=before[:g.start()]+block+before[g.end():];E.fromstring(after)
 for old in re.findall(r'<exercise\b.*?</exercise>',before,re.S):assert old in after
 (ROOT/rp).write_text(json.dumps(dict(id=rid,status='applied-maintainer-approved',target_release='cp2e-ver1.1',module=mid,source_path=p.relative_to(ROOT).as_posix(),source_sha256=sha(before),after_sha256=sha(after),before=before,after=after,additions=added,exercise_order=order,reason='Five approved MyOpenMath-guided additions; reorder Chapter 3 questions by section topic sequence. Preserve all existing question text and IDs, including approved Exercises 7–8 revisions.'),ensure_ascii=False,indent=2)+'\n',encoding='utf8');p.write_text(after,encoding='utf8');ledger['changes'].append(rp.as_posix())
lp.write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n',encoding='utf8');(ROOT/'reports/1.1/chapter3-structure/exercise-additions-and-order.json').write_text(json.dumps(dict(additions=provenance,chapter_exercises=25,source_orders=orders,notes=['20 existing exercises retained unchanged in this ordering pass.','Two Check Your Understanding prompts and their answers remain inline.','No new media imported; path comparison references Figure 3.5.1.']),ensure_ascii=False,indent=2)+'\n',encoding='utf8');print('Added five questions; ordered 25; preserved existing content and IDs.')
