"""Read-only deeper audit of m67127; generates review proposals, not source edits."""
from pathlib import Path
import xml.etree.ElementTree as E,json,html,sys,copy,hashlib
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'prototype'))
from native_math import native_math
C='{http://cnx.rice.edu/cnxml}';M='{http://www.w3.org/1998/Math/MathML}'
root=E.parse(ROOT/'maintained/modules/m67127/index.cnxml').getroot();ids={e.get('id'):e for e in root.iter() if e.get('id')}
items=[]
MIT='https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node37.html'
OTTO='https://web.mit.edu/16.unified/www/SPRING/propulsion/notes/node25.html'
EIA='https://www.eia.gov/tools/faqs/faq.php?id=72'
NIST='https://webbook.nist.gov/cgi/cbook.cgi?ID=C124389&Units=SI&Mask=1'
def plain(e):
 if e.tag==M+'annotation':return ''
 return (e.text or '')+''.join(plain(c)+(c.tail or '') for c in e)
def add(key,title,reason,changes,sources,priority='correction proposed'):
 obj=dict(id=key,title=title,status=priority,reason=reason,sources=sources,changes=[])
 for ident,after in changes:
  obj['changes'].append(dict(source_id=ident,before_xml=E.tostring(ids[ident],encoding='unicode'),proposed_text=after))
 items.append(obj);return obj
add('HE01','Specify which object gets hotter','This is in the adapted opening. One object warming while the other cools is normal if heat flows from hot to cold. The intended reversed process needs just two identifying words. Preserve the rest of the rewritten introduction.', [('import-auto-id1169738147207','Replace “two objects in thermal contact where one gets hotter and the other gets colder” with “two objects in thermal contact where the hotter one gets hotter and the colder one gets colder”.')],[MIT])
second='It is impossible for a system operating in a cycle to have as its sole result the absorption of heat from a single reservoir and the conversion of all that heat into work.'
add('HE02','Make the formal heat-engine statement complete','The heat-engine box should specify the sole result, not merely return of the engine to its initial state. Coordinate the summary and repair the glossary, whose “never the reverse” omits spontaneously. The first expression and its immediately following sole-result version are already sound.', [('eip-id1423437',second),('import-auto-id1169738234744','Retain statement (i) and the concluding sentence. Replace statement (ii) with: '+second),('fs-id1169738014671','heat does not spontaneously flow from a cooler to a hotter object, and no cyclic engine can convert heat from a single reservoir entirely into work as its sole result')],[MIT])
add('HE03','Keep heat-engine qualifications and heat notation local','“In all processes” and the general conversion-of-energy opening are overbroad. The signed net Q is distinct from the positive magnitudes Q_h and Q_c. Small substitutions suffice.', [('import-auto-id1169737992344','Replace “in all processes” with “in a heat-engine cycle”.'),('import-auto-id1169737966671','Replace the first sentence with “In a heat engine, only part of the heat input is converted to work.” Retain the efficiency definition that follows.'),('import-auto-id1169738014694','Replace “Note that all Qs are positive.” with “Here Q_h and Q_c are positive amounts of heat transfer.” Retain the following sign explanation.')],[MIT,OTTO])
add('HE04','Repair the coal/CO₂ example together','The work (1.02 × 10^14 J), efficiency (40.8%), and power (1180 MW) are correct. But 2.5 × 10^6 J/kg is far below the ordinary coal heating-value scale (tens of MJ/kg), and the 44/12 mass ratio applies to carbon, not arbitrary coal. The displayed 10^8 kg results also conflict with their retained StarMath annotations, which say 10^7. This is a substantive inherited numerical/model error, not a rounding issue.', [('import-auto-id1169737780262','Recommended replacement for part (c) only: “For a simplified estimate, treat the fuel as pure carbon, releasing 3.3 × 10^7 J/kg when burned completely to CO₂. The reaction C + O₂ → CO₂ produces 44 kg of CO₂ for every 12 kg of carbon. How much CO₂ is emitted per day in this model?” Keep the setup and parts (a) and (b).'),('eip-825','Use “carbon” consistently in the part (c) strategy and state the pure-carbon model there. Do not imply all real coal is pure carbon.'),('eip-238','Daily carbon consumption: (2.50 × 10^14 J)/(3.3 × 10^7 J/kg) = 7.6 × 10^6 kg.'),('import-auto-id1169737739559','For complete combustion of this carbon, CO₂ produced per day = (7.6 × 10^6 kg)(44/12) = 2.8 × 10^7 kg.'),('import-auto-id1169738213149','This is about 28,000 metric tons of CO₂ produced per day in this simplified model.')],[EIA,NIST],'maintainer decision: coordinated example revision')
items[-1]['alternative']='If preserving a coal-specific estimate is preferable, specify both its heat content and carbon mass fraction. Changing only the exponent to 10^7 gives 37,000 tonnes but still treats every kilogram of coal as carbon. No choice has been applied.'
add('HE05','Separate waste heat, greenhouse emissions, and efficiency','The current discussion blends local heat rejection with global greenhouse warming and calls carbon intensity efficiency. Preserve the cogeneration point. Remove the unanchored 42% benchmark and broad claim about the economics of most engines, rather than inserting dated statistics.', [('eip-567','If all the work output is converted to electricity in a period of one day, the average power output is 1180 MW (this is left to you as an end-of-chapter problem). This value is about the size of a large-scale conventional power plant. The efficiency is 40.8%, so 59.2% of the heat input is transferred to the environment. This can warm nearby bodies of water used for cooling. While the laws of thermodynamics limit the efficiency of such plants—including plants fired by nuclear fuel, oil, and natural gas—the heat transfer to the environment could be, and sometimes is, used for heating homes or for industrial processes. Coal combustion also releases CO₂, which contributes to global warming. Coal generally produces more CO₂ per unit of heat released than oil or natural gas.')],['https://www.epa.gov/energy/combined-heat-and-power','https://www.eia.gov/tools/faqs/faq.php?id=73&t=11','https://19january2017snapshot.epa.gov/climate-change-science/causes-climate-change_.html'])
add('HE06','Distinguish the closed Otto model from the actual engine','The gasoline–air mixture does not return to its original condition: combustion products are expelled and replaced. In the closed ideal model, heat addition/rejection represents combustion and gas exchange. In an actual engine, exhaust carries energy out with matter.', [('import-auto-id1169736614771','Replace its final sentence with “The four steps shown complete the engine’s operating cycle, replacing the exhaust gases with a fresh gasoline-air mixture.”'),('import-auto-id1169737933345','The ideal Otto cycle shown in the figure models a fixed amount of gas undergoing two adiabatic and two constant-volume processes. It approximates the operation of a four-stroke internal combustion engine, although its paths do not correspond exactly to the strokes of the engine.'),('import-auto-id1169738110852','Keep the AB/BC/CD explanation. Replace the final two sentences with: “In an internal combustion engine, this part of the model represents the exhaust of hot gases and the intake of a cooler air-gasoline mixture. The actual engine carries energy out with the exhaust; the ideal cycle represents this by heat transfer from the gas.”')],[OTTO,'https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/engine-thermodynamic-analysis/'])
add('HE07','Do not infer efficiency from the area alone','Greater loop area establishes greater net work, not higher W/Q_h. For the ideal Otto cycle with constant heat capacities, efficiency is 1 − r^(1−γ). At the same compression ratio and γ, changing the temperature scale or increasing heat input does not improve that efficiency. The two displayed cycles retain the same volume limits. Also scope the no-heat return-path statement to this reversible adiabatic model.', [('import-auto-id1169736654385','The net work done by a cyclical process is the area inside the closed path on a PV diagram, such as that inside path ABCDA in [existing figure reference]. A heat-engine cycle must reject some of its heat input. In the Otto cycle, this heat transfer occurs along path DA. Simply retracing the reversible adiabatic expansion would give no net work output. Lower pressure along AB reduces the compression work, while higher pressure along CD increases the expansion work. These changes increase the net work output of the Otto cycle. The maximum possible efficiency of a heat engine operating between two heat reservoirs increases when the hot reservoir is hotter or the cold reservoir is colder. In the next section, we shall see how these reservoir temperatures set the upper limit to efficiency.')],[OTTO],'important conceptual correction')
add('HE08','Coordinate the glossary','Keep the adapted rejection of path-dependence as a definition of irreversibility. Clarify that restoration must include surroundings. Define Otto cycle as the ideal model, rather than equating its four thermodynamic legs with the engine strokes.', [('fs-id1169737907449','a process that cannot be reversed so as to restore both the system and its surroundings to their initial states'),('fs-id1169737949805','an ideal heat-engine cycle consisting of two reversible adiabatic processes and two constant-volume processes, used to model a spark-ignition engine')],[MIT,OTTO])
verified=[
 'The first second-law expression and its sole-result restatement are correct in this context.',
 'The cycle identities ΔU = 0, W = Q_h − Q_c, and Eff = W/Q_h = 1 − Q_c/Q_h are correct with the stated heat-engine sign convention.',
 'Recalculation: 2.50e14 − 1.48e14 = 1.02e14 J; 1.02/2.50 = 0.408; 1.02e14/86400 = 1.1806e9 W. Rejected fraction = 0.592.',
 'The Pikes Peak conceptual question is consistent to its intended precision: mgh for 1000 kg and 100 m is 0.981 MJ; 12.5 km implies 122.6 MJ/gallon. No new exercise rewrite is proposed.',
 'The reversible-engine exercise previously retained by the maintainer remains unchanged; the same-reservoir assumption need not be reinserted there.',
 'The heat-engine flow diagram is consistent with its heat/work balance. Otto plots support their net-work comparison; their captions do not themselves assert that larger work means greater efficiency.',
 'The “(a)” reference to the single Otto plot is a minor stale figure label; HE06 removes it. Its right-hand reservoir schematic is a conceptual heat-flow picture, not a claim that the gas remains at constant temperature during the constant-volume legs.',
 'The one-way-process figure and ice photograph are retained. Their macroscopic no-spontaneous-reversal interpretation is adequate here; a broader fluctuation/statistical discussion remains in the separately requested entropy/disorder review.'
]
for item in items:
 if item['id'] in ['HE01','HE02','HE03','HE04','HE05','HE06','HE07','HE08']:
  item['status']='approved-pending-coordinated-application'
  item['authorization']='Maintainer approved HE01–HE06, reaffirmed the pure-carbon model for HE04, and approved revised HE07 connecting Otto work output to the Carnot efficiency limit.'
comparison=json.loads((ROOT/'reports/1.1/heat-engine-review/adaptation-comparison.json').read_text(encoding='utf-8'))
packet=dict(module='m67127',upstream_module='m42234',upstream_commit='f98d7a792138a6133fe7267d17e70aa04e9ccbed',ancestor='m42234/1.4 per recovered attribution',status='HE01–HE08 approved; full-section preview prepared with separate overlays; maintained source unchanged',comparison=comparison,items=items,verified=verified,checks={'maintained_sha256':hashlib.sha256((ROOT/'maintained/modules/m67127/index.cnxml').read_bytes()).hexdigest(),'reviewed':'Body, equations, worked example, figure captions/diagrams, summary, four conceptual questions, and glossary.'})
(ROOT/'proposals/1.1/heat-engine-review.json').write_text(json.dumps(packet,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def render(e):
 if e.tag==M+'math':return native_math(e)[0]
 body=html.escape(e.text or '')+''.join(render(c)+html.escape(c.tail or '') for c in e)
 tag=e.tag.split('}')[-1]
 if tag=='link':return body or '[existing reference]'
 if tag=='emphasis':return '<em>'+body+'</em>'
 if tag in ['para','meaning','item']:return '<p>'+body+'</p>'
 return body
h=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Heat-engine section audit</title><style>body{font:18px/1.6 Georgia;max-width:1200px;margin:auto;padding:24px;color:#24383c}a{color:#075b72}section{border-top:1px solid #abc;margin-top:32px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:18px}.cell{background:#f2f6f7;padding:18px;min-width:0;overflow:auto}.notice{background:#fff3d6;padding:16px}math{font-size:1.05em} @media(max-width:760px){.cols{display:block}}</style><h1>Section 8.10: deeper review</h1><p class="notice">Review proposals only. No textbook changes have been applied. HE01–HE07 are approved, including the pure-carbon model and revised transition to the Carnot efficiency limit. HE08 is also approved. <a href="../priority3-sections/sections/introduction-to-the-second-law-of-thermodynamics-heat-engines-and-their-efficiency/index.html">Read the complete revised section</a>.</p><h2>How much was already adapted?</h2><p>The recovered attribution identifies Andrew Park’s m67127 version 1.3 as based on OpenStax m42234 version 1.4. Against the pinned CC BY 4.0 February 2026 snapshot, 46 of 50 shared identified prose blocks are unchanged (92% by block count, not by words). The four differences are the opening, two summary items, and the irreversible-process glossary definition. All four already occur in the recovered 12.1 source; the maintained version has no additional prose differences in these blocks. This does not prove the exact edit history against ancestor 1.4, which was not independently recovered here.</p><p>Your adaptation removed the upstream path-dependence definition and its claim that irreversible processes cannot return a system to its original state. It also rebuilt the opening with everyday examples. The math comparison records preservation of local U notation; one diagram differs from the pinned upstream image. Those differences are not permission to restore the upstream versions.</p><details><summary>Four original adaptation comparisons</summary>']
for d in comparison['differences']:h.append('<h3>'+d['id']+'</h3><div class="cols"><div class="cell"><h4>Pinned upstream</h4>'+html.escape(d['upstream'])+'</div><div class="cell"><h4>Recovered Introduction to Physics</h4>'+html.escape(d['baseline'])+'</div></div>')
h.append('</details><h2>Corrections for review</h2><ul>'+''.join('<li><a href="#'+i['id']+'">'+i['id']+' — '+html.escape(i['title'])+'</a></li>' for i in items)+'</ul>')
for i in items:
 h.append('<section id="'+i['id']+'"><h2>'+i['id']+' — '+html.escape(i['title'])+'</h2><p><strong>'+html.escape(i['status'])+'</strong></p><p>'+html.escape(i['reason'])+'</p>')
 for ch in i['changes']:
  h.append('<div class="cols"><div class="cell"><h3>Current context</h3>'+render(ids[ch['source_id']])+'</div><div class="cell"><h3>Proposed replacement / edit</h3><p>'+html.escape(ch['proposed_text'])+'</p></div></div>')
 if i.get('alternative'):h.append('<p>'+html.escape(i['alternative'])+'</p>')
 h.append('<p>Evidence: '+' · '.join('<a href="'+html.escape(url,quote=True)+'">'+html.escape(url.split('/')[2])+'</a>' for url in i['sources'])+'</p></section>')
h.append('<h2>Checked and retained</h2><ul>'+''.join('<li>'+html.escape(t)+'</li>' for t in verified)+'</ul><p><a href="/course-full/sections/introduction-to-the-second-law-of-thermodynamics-heat-engines-and-their-efficiency/index.html">Unchanged full section</a> · <a href="../priority3-review/">Priority 3 review</a></p></html>')
for folder in [ROOT/'reports/1.1/heat-engine-review',ROOT/'prototype/dist/review-1.1/heat-engine-review']:
 folder.mkdir(parents=True,exist_ok=True);(folder/'index.html').write_text('\n'.join(h),encoding='utf-8')
print('Prepared eight review groups; no textbook edits applied.')
